config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace 'admin' do
    resources :offers
    post '/offers/:id/change_state', to: 'offers#change_state', as: 'update_offer_state'
  end

  namespace 'user' do
    resources :offers, only: [:index]
  end

  root to: 'admin/offers#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
# frozen_string_literal: true

require 'uri'

class Offer < ApplicationRecord
  validates :advertiser_name, :url, :description, :starts_at, presence: true
  validates :advertiser_name, uniqueness: true
  validates_length_of :description, maximum: 500
  validate :url_format

  before_create :set_default_state
  before_save :set_state

  private

  def set_default_state
    self.state = 'disabled'
  end

  def set_state
    if DateTime.now >= starts_at
      self.state = 'enabled'
    elsif DateTime.now <= ends_at
      self.state = 'disabled'
    elsif ends_at.blank?
      self.state = 'enabled'
    end
  end

  def url_format
    errors.add(:url, :invalid_format) unless url =~ URI::DEFAULT_PARSER.make_regexp
  end
end

app/controllers/admin/offers_controller.rb
# frozen_string_literal: true

module Admin
  class OffersController < ApplicationController
    before_action :set_offer, only: %i[show edit update destroy change_state]

    # GET /offers
    def index
      @offers = Offer.order(:created_at).all
    end

    # GET /offers/1
    def show; end

    # GET /offers/new
    def new
      @offer = Offer.new
    end

    # GET /offers/1/edit
    def edit; end

    # POST /offers
    def create
      @offer = Offer.new(offer_params)
      respond_to do |format|
        if @offer.save
          format.html { redirect_to admin_offers_path, notice: 'Offer was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT /offers/1
    def update
      respond_to do |format|
        if @offer.update(offer_params)
          format.html { redirect_to admin_offers_path, notice: 'Offer was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    # DELETE /offers/1
    def destroy
      @offer.destroy
      respond_to do |format|
        format.html { redirect_to admin_offers_path, notice: 'Offer was successfully destroyed.' }
      end
    end

    # POST /offers/1/change_state
    def change_state
      if @offer.state == 'enabled'
        respond_to do |format|
          if @offer.update_column(:state, 'disabled')
            format.html { redirect_to admin_offers_path, notice: 'Offer State was successfully updated.' }
          else
            format.html { redirect_to admin_offers_path, notice: 'Offer State cannot be updated.' }
          end
        end
      else
        @offer.state = 'enabled'
        respond_to do |format|
          if @offer.save!
            notice = @offer.state == 'disabled' ? 'Offer State cannot be updated because of some validation rule.' : 'Offer State updated with success'
            format.html { redirect_to admin_offers_path, notice: notice }
          end
        end
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offer_params
      params.require(:offer).permit(:advertiser_name, :url, :description, :starts_at, :ends_at, :premium, :state)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy, :change_state]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change_state
    if @offer.state == "enabled"
      @offer.update_column(:state,"disabled")
    else
      @offer.update_column(:state, "enabled")
    end
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer State was successfully updated.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offer_params
      params.require(:offer).permit(:advertiser_name, :url, :description, :starts_at, :ends_at, :premium, :state)
    end
end

app/controllers/user/offers_controller.rb
# frozen_string_literal: true

module User
  class OffersController < ApplicationController
    def index
      @offers = Offer.where(state: 'enabled').order(premium: :desc)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/offers_helper.rb
# frozen_string_literal: true

module OffersHelper
end

app/views/admin/offers/_form.html.erb
<%= form_for [:admin, @offer], :html => { :class => "form-horizontal offer" } do |f| %>

  <% if @offer.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @offer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :advertiser_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :advertiser_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:advertiser_name) %>
  </div>
  <div class="form-group">
    <%= f.label :url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :url, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :starts_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :starts_at, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ends_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :ends_at, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :premium, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.check_box :premium, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_offers_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/admin/offers/edit.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/offers/index.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:advertiser_name) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:starts_at) %></th>
      <th><%= model_class.human_attribute_name(:ends_at) %></th>
      <th><%= model_class.human_attribute_name(:premium) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= link_to offer.id, admin_offer_path(offer) %></td>
        <td><%= offer.advertiser_name %></td>
        <td><%= offer.url %></td>
        <td><%= offer.description %></td>
        <td><%= offer.starts_at %></td>
        <td><%= offer.ends_at %></td>
        <td><%= offer.premium %></td>
        <td><%= offer.state %></td>
        <td><%=l offer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_admin_offer_path(offer), :class => 'btn btn-default btn-xs' %>

          <% if offer.state == "disabled" %>
            <%= link_to t('.enable', :default => t("helpers.links.enable")),
              admin_update_offer_state_path(offer), method: :post, :class => 'btn btn-default btn-xs' %>
          <% else %>
            <%= link_to t('.disable', :default => t("helpers.links.disable")),
              admin_update_offer_state_path(offer), method: :post, :class => 'btn btn-default btn-xs' %>
          <% end %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_offer_path(offer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_offer_path,
            :class => 'btn btn-primary' %>

app/views/admin/offers/new.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/offers/show.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:advertiser_name) %>:</strong></dt>
  <dd><%= @offer.advertiser_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @offer.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @offer.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:starts_at) %>:</strong></dt>
  <dd><%= @offer.starts_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ends_at) %>:</strong></dt>
  <dd><%= @offer.ends_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:premium) %>:</strong></dt>
  <dd><%= @offer.premium %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              offers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_offer_path(@offer), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              offer_path(@offer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/offers/_form.html.erb
<%= form_for @offer, :html => { :class => "form-horizontal offer" } do |f| %>

  <% if @offer.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @offer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :advertiser_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :advertiser_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:advertiser_name) %>
  </div>
  <div class="form-group">
    <%= f.label :url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :url, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :starts_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :starts_at, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ends_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :ends_at, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :premium, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.check_box :premium, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                offers_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/offers/index.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:advertiser_name) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:starts_at) %></th>
      <th><%= model_class.human_attribute_name(:ends_at) %></th>
      <th><%= model_class.human_attribute_name(:premium) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= link_to offer.id, offer_path(offer) %></td>
        <td><%= offer.advertiser_name %></td>
        <td><%= offer.url %></td>
        <td><%= offer.description %></td>
        <td><%= offer.starts_at %></td>
        <td><%= offer.ends_at %></td>
        <td><%= offer.premium %></td>
        <td><%= offer.state %></td>
        <td><%=l offer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_offer_path(offer), :class => 'btn btn-default btn-xs' %>

          <% if offer.state == "disabled" %>
            <%= link_to t('.enable', :default => t("helpers.links.enable")),
              update_offer_state_path(offer), method: :post, :class => 'btn btn-default btn-xs' %>
          <% else %>
            <%= link_to t('.disable', :default => t("helpers.links.disable")),
              update_offer_state_path(offer), method: :post, :class => 'btn btn-default btn-xs' %>
          <% end %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      offer_path(offer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_offer_path,
            :class => 'btn btn-primary' %>

app/views/user/offers/index.html.erb
<div class="box">
  <div class="container">
    <div class="row">
      <% @offers.each do |offer| %>
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <div class="box-part text-center">
          <i class="fa fa-instagram fa-3x" aria-hidden="true"></i>
          <div class="title">
            <h4><%= offer.advertiser_name %></h4>
          </div>
          <% if offer.premium %>
            <div class="text">
              <img src="https://www.teclasap.com.br/wp-content/uploads/2005/05/premium.png" width="45%" height="100%">
            </div>
          <% end %>
          <h3> <a href="<%= offer.url %>">Click Here!</a> </h3>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>